sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t catalina .
      - docker images
      - docker tag catalina $DOCKER_USERNAME/catalina
      - docker push $DOCKER_USERNAME/catalina
